spring:
  datasource:
#    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

#    pool:
#      initial-size: 3
#      max-size: 10
#      max-idle-time: 30m
  jooq:
    sql-dialect: postgres

  jackson:
    default-property-inclusion: always
    property-naming-strategy: SNAKE_CASE
    deserialization:
      adjust-dates-to-context-time-zone: false
      fail-on-null-for-primitives: false
      fail-on-unknown-properties: false
    mapper:
      accept-case-insensitive-properties: true
    serialization:
      write-dates-as-timestamps: false
